# phiPoint2D.coffee
#
# Exact 2D positions in Z[φ] using a non-orthogonal basis:
#   p = a · e₀ + b · e₇₂
# where e₀ is the unit vector at 0° and e₇₂ the unit vector at 72°.
#
# Why this works (and why straight Cartesian xy doesn't):
#   Cartesian positions for Robinson tiles involve sin/cos of 36° multiples,
#   and sin(36°) ∉ Q[φ]. In the (e₀, e₇₂) basis, however, rotation by 36°
#   is a 2×2 matrix entirely over Z[φ]:
#       R₃₆ e₀  = (φ−1, φ−1)
#       R₃₆ e₇₂ = (1−φ, 1)
#   so every position generated by stepping along Robinson-edge directions
#   stays exactly in Z[φ]². Vertex identity is exact PhiBase equality.
#   Float touches nothing until SVG render.
#
# This module is self-contained — no fetch, no init. Just classes and
# precomputed constants.

import { PhiBase } from '$lib/coffee/phiBase.coffee'

PHI_PB           = new PhiBase(1, 0)   # φ
ONE_PB           = new PhiBase(0, 1)   # 1
ZERO_PB          = new PhiBase(0, 0)   # 0
PHI_MINUS_1      = new PhiBase(1, -1)  # φ − 1 = 1/φ
ONE_MINUS_PHI    = new PhiBase(-1, 1)  # 1 − φ = −1/φ
NEG_ONE_PB       = new PhiBase(0, -1)  # −1

# PHI value for use ONLY in Cartesian conversion (SVG render).
PHI_FLOAT  = (1 + Math.sqrt(5)) / 2
COS72      = (PHI_FLOAT - 1) / 2                 # = 1/(2φ) ≈ 0.309
SIN72      = Math.sqrt(2 + PHI_FLOAT) / 2        # ≈ 0.951

export class PhiPoint2D
  constructor: (@a, @b) ->                       # a, b: PhiBase

  clone: -> new PhiPoint2D(@a.clone(), @b.clone())

  add: (other) -> new PhiPoint2D(@a.add(other.a), @b.add(other.b))
  sub: (other) -> new PhiPoint2D(@a.sub(other.a), @b.sub(other.b))
  neg: ->        new PhiPoint2D(@a.mul(NEG_ONE_PB), @b.mul(NEG_ONE_PB))

  # Scale by a PhiBase scalar.
  scale: (s) -> new PhiPoint2D(@a.mul(s), @b.mul(s))

  # Length comparison stays exact: |p|² = a² + (φ−1)·ab + b².
  # (Derived from |a·e₀+b·e₇₂|² = a² + 2ab·cos(72°) + b² and
  # 2·cos(72°) = φ−1.)
  magSquared: ->
    @a.mul(@a).add(PHI_MINUS_1.mul(@a).mul(@b)).add(@b.mul(@b))

  # 2 × (p · other) — the Cartesian dot product, doubled, exact in Z[φ].
  # In the (e₀, e₇₂) basis:
  #   p · q = a·a' + b·b' + (a·b' + a'·b) · cos(72°)
  # With 2·cos(72°) = φ−1 the doubling clears the /2 and keeps Z[φ]:
  #   2(p · q) = 2(a·a' + b·b') + (a·b' + a'·b) · (φ−1)
  # Used by half-plane tests (e.g. the pentagonal canvas boundary): the
  # threshold is stored doubled too, so all comparisons stay integer Z[φ].
  twoDot: (other) ->
    ac    = @a.mul(other.a).add(@b.mul(other.b))
    cross = @a.mul(other.b).add(@b.mul(other.a))
    ac.mul(new PhiBase(0, 2)).add(cross.mul(PHI_MINUS_1))

  # Exact equality.
  equals: (other) ->
    @a.equals(other.a) and @b.equals(other.b)

  # String key for use in Maps / Sets / dedup. Uses PhiBase.toID().
  key: -> "#{@a.toID()}|#{@b.toID()}"

  # Rotate this point about the origin by +36° (CCW). Implements the matrix
  #   R₃₆ = | φ−1   1−φ |
  #         | φ−1    1  |
  # i.e. (a, b) ↦ ((φ−1)(a−b), (φ−1)a + b). Stays exactly in Z[φ].
  rotate36: ->
    aPrime = PHI_MINUS_1.mul(@a.sub(@b))
    bPrime = PHI_MINUS_1.mul(@a).add(@b)
    new PhiPoint2D(aPrime, bPrime)

  # Rotate by k × 36° (CCW). k is integer (negative or > 10 OK).
  rotate36k: (k) ->
    k = ((k % 10) + 10) % 10
    p = @clone()
    p = p.rotate36() for _ in [0...k]
    p

  # Convert to Cartesian floats. **Only for SVG render.** Never call this
  # from legality / vertex-identity paths.
  toCartesian: ->
    af = @a.toFloat()
    bf = @b.toFloat()
    [af + bf * COS72, bf * SIN72]

  toString: -> "(#{@a.toString()}, #{@b.toString()})"

# Static constants (assigned after the class definition because CoffeeScript
# doesn't allow `@FOO = ...` at the class body to reference its own ctor in
# all bundler configurations).
PhiPoint2D.ZERO = new PhiPoint2D(ZERO_PB, ZERO_PB)
PhiPoint2D.E0   = new PhiPoint2D(ONE_PB,  ZERO_PB)
PhiPoint2D.E72  = new PhiPoint2D(ZERO_PB, ONE_PB)

# --- Precomputed unit displacements ------------------------------------
#
# UNIT_DISP[k] is a unit vector at angle (k × 36°), expressed exactly in the
# (e₀, e₇₂) basis. LONG_DISP[k] = φ · UNIT_DISP[k] (length φ in same
# direction). Derived by repeated rotation; verified against Cartesian.

UNIT_DISP = [
  # k=0,    0°: (1, 0)
  new PhiPoint2D(ONE_PB, ZERO_PB)
  # k=1,   36°: (φ−1, φ−1)
  new PhiPoint2D(PHI_MINUS_1, PHI_MINUS_1)
  # k=2,   72°: (0, 1)
  new PhiPoint2D(ZERO_PB, ONE_PB)
  # k=3,  108°: (1−φ, 1)
  new PhiPoint2D(ONE_MINUS_PHI, ONE_PB)
  # k=4,  144°: (−1, φ−1)
  new PhiPoint2D(NEG_ONE_PB, PHI_MINUS_1)
  # k=5,  180°: (−1, 0)
  new PhiPoint2D(NEG_ONE_PB, ZERO_PB)
  # k=6,  216°: (1−φ, 1−φ)
  new PhiPoint2D(ONE_MINUS_PHI, ONE_MINUS_PHI)
  # k=7,  252°: (0, −1)
  new PhiPoint2D(ZERO_PB, NEG_ONE_PB)
  # k=8,  288°: (φ−1, −1)
  new PhiPoint2D(PHI_MINUS_1, NEG_ONE_PB)
  # k=9,  324°: (1, 1−φ)
  new PhiPoint2D(ONE_PB, ONE_MINUS_PHI)
]

LONG_DISP = (d.scale(PHI_PB) for d in UNIT_DISP)

# Unit vector at angle (k × 36°). k normalised to 0..9.
export getUnitDisp = (k) ->
  UNIT_DISP[((k % 10) + 10) % 10]

# Long vector (length φ) at angle (k × 36°).
export getLongDisp = (k) ->
  LONG_DISP[((k % 10) + 10) % 10]

# Identify a non-zero displacement vector as one of our 20 known
# directions, *at a given tileScale*. With tileScale = ONE_PB (= 1) the
# match is against the canonical UNIT_DISP/LONG_DISP. With a smaller
# tileScale (e.g. PhiBase(1, -1) = 1/φ), the tables are scaled to match
# the smaller lattice unit.
#
# Returns { dir: k, len: 'short' | 'long' } or null.
export classifyDisplacement = (disp, tileScale = ONE_PB) ->
  unitTbl = if tileScale.equals(ONE_PB) then UNIT_DISP else (d.scale(tileScale) for d in UNIT_DISP)
  longTbl = if tileScale.equals(ONE_PB) then LONG_DISP else (d.scale(tileScale) for d in LONG_DISP)
  for d, k in unitTbl
    return { dir: k, len: 'short' } if d.equals(disp)
  for d, k in longTbl
    return { dir: k, len: 'long' } if d.equals(disp)
  null

# Convenience: given two PhiPoint2D vertices, classify the displacement
# from v0 to v1.
export edgeDirection = (v0, v1, tileScale) ->
  classifyDisplacement(v1.sub(v0), tileScale)

# Signed 2x area of triangle (P, Q, R) — uses the cross-product formula in
# the (e₀, e₇₂) basis. The actual oriented area is this value × sin(72°),
# but for orientation tests (CCW/CW) we only need the sign, and that's
# determined exactly by this PhiBase value's sign. Returns a PhiBase.
export signedArea2 = (P, Q, R) ->
  # cross(Q−P, R−P) in 2D = (Qx−Px)(Ry−Py) − (Qy−Py)(Rx−Px)
  # In our basis "x" coords are .a and "y" coords are .b (treating the
  # basis as oblique but consistent for sign-of-cross tests since e₀×e₇₂
  # is a fixed positive scalar).
  d1a = Q.a.sub(P.a)
  d1b = Q.b.sub(P.b)
  d2a = R.a.sub(P.a)
  d2b = R.b.sub(P.b)
  d1a.mul(d2b).sub(d1b.mul(d2a))
