// Generated by CoffeeScript 2.7.0
export var Memo = class Memo {
  constructor() {
    this.memoLog = this.memoLog.bind(this);
    this.theLowdown = this.theLowdown.bind(this);
    this.waitFor = this.waitFor.bind(this);
    this.notifyMe = this.notifyMe.bind(this);
    this.MM = {};
  }

  memoLog(key) {
    return console.log(`Snapping ${key}`, this.MM[key]);
  }

  saveThis(key, value) {
    var breaker, maybe, oldResolver, ref, ref1;
    if (this.MM[key] !== void 0 && value === this.MM[key].value) {
      return this.MM[key];
    }
    oldResolver = (ref = (ref1 = this.MM[key]) != null ? ref1.resolver : void 0) != null ? ref : null;
    breaker = null;
    maybe = new Promise((resolve, reject) => {
      return breaker = resolve;
    });
    this.MM[key] = {
      value: value,
      notifier: maybe,
      resolver: breaker
    };
    if (oldResolver) { //notify subscribers of new cache value
      oldResolver(this.MM[key]);
    }
    return this.MM[key];
  }

  theLowdown(key) {
    if (this.MM[key] !== void 0) {
      return this.MM[key];
    }
    return this.saveThis(key, null);
  }

  waitFor(aList, andDo) {
    var d, dependants, key, unfound;
    unfound = [];
    dependants = (function() {
      var i, len, results;
      results = [];
      for (i = 0, len = aList.length; i < len; i++) {
        key = aList[i];
        d = this.theLowdown(key);
        if (d.value === null) {
          unfound.push(d.notifier);
        }
        results.push(d.notifier);
      }
      return results;
    }).call(this);
    if (unfound.length > 0) {
      Promise.allSettled(unfound).then(andDo);
    }
    return Promise.any(dependants).then(andDo);
  }

  async notifyMe(n, andDo) {
    var currentValue, newValue, results;
    newValue = (this.theLowdown(n)).value;
    results = [];
    while (true) {
      currentValue = newValue;
      andDo(newValue);
      results.push((await (async function() {
        var results1;
        results1 = [];
        while (currentValue === newValue) {
          results1.push(newValue = ((await this.MM[n].notifier)).value);
        }
        return results1;
      }).call(this)));
    }
    return results;
  }

};
