// Generated by CoffeeScript 2.7.0
var a, b, c, d, e, memo, phi, phiKey, retrievedPhi, sixVector, vectorKey;

import {
  Memo
} from './memo.js';

memo = new Memo();

phi = (1 + Math.sqrt(5)) / 2;

export var PhiBase = class PhiBase {
  constructor(p1, x1) {
    this.p = p1;
    this.x = x1;
  }

  // Addition: (p₁,x₁) + (p₂,x₂) = (p₁+p₂, x₁+x₂)
  add(other) {
    return new PhiBase(this.p + other.p, this.x + other.x);
  }

  // Subtraction: (p₁,x₁) - (p₂,x₂) = (p₁-p₂, x₁-x₂)
  sub(other) {
    return new PhiBase(this.p - other.p, this.x - other.x);
  }

  // Multiply two PhiBase numbers exactly:
  // (p₁φ + x₁) * (p₂φ + x₂) = (p₁x₂ + p₂x₁ + p₁p₂)φ + (x₁x₂ + p₁p₂)
  mul(other) {
    var newP, newX;
    newP = this.p * other.x + this.x * other.p + this.p * other.p;
    newX = this.x * other.x + this.p * other.p;
    return new PhiBase(newP, newX);
  }

  // Multiply by an integer n:
  mulInt(n) {
    return new PhiBase(this.p * n, this.x * n);
  }

  // Conjugate: φ ↦ (1 - φ), thus (p,x) ↦ (-p, x+p)
  conjugate() {
    return new PhiBase(-this.p, this.x + this.p);
  }

  // Norm: N(pφ+x) = (pφ+x)*(p(1-φ)+x+p) is integer: x² + x*p - p²
  norm() {
    return (this.x * this.x) + (this.x * this.p) - (this.p * this.p);
  }

  // Division: a/b = a * conjugate(b) / norm(b)
  div(other) {
    var normB, numerator;
    normB = other.norm();
    if (normB === 0) {
      throw new Error("Divide by zero");
    }
    numerator = this.mul(other.conjugate());
    return new PhiBase(numerator.p / normB, numerator.x / normB);
  }

  // Exact equality check
  equals(other) {
    return this.p === other.p && this.x === other.x;
  }

  // Convert PhiBase number exactly to floating-point for final display only.
  value() {
    return this.p * phi + this.x;
  }

  // Friendly string representation: p(p,x)
  toString() {
    return `p(${this.p},${this.x})`;
  }

};

// Storing and retrieving PhiBase pairs
phiKey = "P1,2"; // φ*1 + 2 exactly

memo.saveThis(phiKey, new PhiBase(1, 2));

// Retrieve exactly later
retrievedPhi = memo.theLowdown(phiKey).value;

console.log(retrievedPhi.toString()); // Outputs: "p(1,2)"


// Storing six-basis vectors exactly
vectorKey = "V1-2,2-1-1,0";

sixVector = [1, -2, 2, -1, -1, 0];

memo.saveThis(vectorKey, sixVector);

// Wait asynchronously for a dependent computation:
memo.waitFor(["P1,2", "V1-2,2-1-1,0"], function() {
  var phiVal, vecVal;
  phiVal = memo.theLowdown("P1,2").value;
  vecVal = memo.theLowdown("V1-2,2-1-1,0").value;
  return console.log("Values ready:", phiVal.toString(), vecVal);
});

// Additional methods for convenience
Memo.prototype.savePhiBase = function(p, x) {
  var key;
  key = `P${p},${x}`;
  return this.saveThis(key, new PhiBase(p, x));
};

Memo.prototype.getPhiBase = function(p, x) {
  var key;
  key = `P${p},${x}`;
  return this.theLowdown(key).value;
};

Memo.prototype.saveSixVector = function(vec) {
  var key;
  key = `V${vec.join(',')}`;
  return this.saveThis(key, vec);
};

Memo.prototype.getSixVector = function(vec) {
  var key;
  key = `V${vec.join(',')}`;
  return this.theLowdown(key).value;
};

a = new PhiBase(2, 3);

b = new PhiBase(-1, 5);

console.log("a:", a.toString()); // "p(2,3)"

console.log("b:", b.toString()); // "p(-1,5)"

c = a.add(b);

console.log("a+b:", c.toString()); // "p(1,8)"

d = a.mul(b);

console.log("a*b:", d.toString()); // Calculated exactly

e = a.div(b);

console.log("a/b:", e.toString()); // Exact division result

console.log("a equals b?", a.equals(b)); // false
