// Generated by CoffeeScript 2.7.0
(function() {
  var SixVector, phi, v, v2,
    indexOf = [].indexOf;

  phi = (1 + Math.sqrt(5)) / 2;
  debugger;
  
window.SixVector = (function() {
    var _Class;

    _Class = class {
      constructor(input) {
        var c, i, k, len;
        // input can be:
        // - full array of 6 coefficients: [c0..c5]
        // - or 3 entries: [[index0, c0], [index1, c1], [index2, c2]]
        if (input.length === 6) {
          this.coeffs = input.slice();
          this.isComplete = true;
        } else if (input.length === 3) {
          this.coeffs = [0, 0, 0, 0, 0, 0];
          this.isComplete = false;
          for (k = 0, len = input.length; k < len; k++) {
            [i, c] = input[k];
            this.coeffs[i] = c;
          }
        } else {
          throw new Error("Invalid SixVector input: must be 6 numbers or 3 [index, value] pairs.");
        }
      }

      complete() {
        var A, D, _, b, c, det, i, k, known, knownVec, l, len, makeMat, unused, used, x, y, z;
        if (this.isComplete) {
          return;
        }
        known = [];
        for (i = k = 0; k <= 5; i = ++k) {
          if (this.coeffs[i] !== 0) {
            known.push([i, this.coeffs[i]]);
          }
        }
        if (known.length !== 3) {
          throw new Error("Cannot complete SixVector: must have exactly 3 known coefficients.");
        }
        used = (function() {
          var l, len, results;
          results = [];
          for (l = 0, len = known.length; l < len; l++) {
            [i, _] = known[l];
            results.push(i);
          }
          return results;
        })();
        knownVec = [0, 0, 0];
        for (l = 0, len = known.length; l < len; l++) {
          [i, c] = known[l];
          b = SixVector.basis[i];
          knownVec = [knownVec[0] + c * b[0], knownVec[1] + c * b[1], knownVec[2] + c * b[2]];
        }
        // Solve A * x = -knownVec using the unused basis vectors
        unused = (function() {
          var m, ref, results;
          results = [];
          for (i = m = 0; m <= 5; i = ++m) {
            if (ref = !i, indexOf.call(used, ref) >= 0) {
              results.push(i);
            }
          }
          return results;
        })();
        A = unused.map(function(i) {
          return SixVector.basis[i];
        });
        det = function(M) {
          return M[0][0] * (M[1][1] * M[2][2] - M[1][2] * M[2][1]) - M[0][1] * (M[1][0] * M[2][2] - M[1][2] * M[2][0]) + M[0][2] * (M[1][0] * M[2][1] - M[1][1] * M[2][0]);
        };
        makeMat = function(col) {
          return A.map(function(row, i) {
            return row.map(function(v, j) {
              if (j === col) {
                return -knownVec[i];
              } else {
                return v;
              }
            });
          });
        };
        D = det(A);
        if (Math.abs(D) < 1e-10) {
          throw new Error("Degenerate basis system");
        }
        x = det(makeMat(0)) / D;
        y = det(makeMat(1)) / D;
        z = det(makeMat(2)) / D;
        this.coeffs[unused[0]] = x;
        this.coeffs[unused[1]] = y;
        this.coeffs[unused[2]] = z;
        return this.isComplete = true;
      }

      toCartesian() {
        var b, c, i, k, result;
        if (!this.isComplete) {
          this.complete();
        }
        result = [0, 0, 0];
        for (i = k = 0; k <= 5; i = ++k) {
          b = SixVector.basis[i];
          c = this.coeffs[i];
          result = [result[0] + c * b[0], result[1] + c * b[1], result[2] + c * b[2]];
        }
        return result;
      }

      toString() {
        return `6-vector: [${this.coeffs.map(function(x) {
          return x.toFixed(3);
        }).join(', ')}]\nCartesian: [${this.toCartesian().map(function(x) {
          return x.toFixed(3);
        }).join(', ')}]`;
      }

    };

    // Static basis shared across all instances
    _Class.basis = [[phi, 0, 1], [phi, 0, -1], [0, 1, phi], [0, -1, phi], [1, phi, 0], [-1, phi, 0]];

    return _Class;

  }).call(this);

  // From 3 known coefficients
  v = new SixVector([[0, 1], [2, 2], [4, -1]]);

  console.log(v.toString());

  // From full 6-vector
  v2 = new SixVector([1, -1, 0, 0, 0, 0]);

  console.log(v2.toCartesian());

}).call(this);
