# tables.tcl — GENERATED by tools/genTables.coffee. Do not edit.
# |G| = 60  (1 identity + 24 face + 20 vertex + 15 flip)
# Group closure verified: all 60x60 = 3600 products stay in the group.
# Element orders verified: R_X^5 = R_TRIP^3 = flip^2 = identity.
# Chirality (§6.7): PASS on dodecahedron1, FAIL on dodecahedron2 (correctly discriminated)
# Each entry has FOUR fields: {coord_perm coord_signs basis_perm basis_signs}.
# Coordinate action (applied to heading/position SixPhi vectors):
#   v'[k] = coord_signs[k] * v[coord_perm[k]]
# Basis action (applied to floor as a signed axis index (i, s)):
#   (i, s) -> (basis_perm[i], s * basis_signs[i])

namespace eval ::tab {}
array set ::tab::rot {}

set ::tab::rot(id) [list [list 0 1 2 3 4 5] [list 1 1 1 1 1 1] [list 0 1 2 3 4 5] [list 1 1 1 1 1 1]]

# --- 24 face-axis 5-fold rotations ---
set ::tab::rot(A1) [list [list 0 2 4 1 5 3] [list 1 1 1 -1 1 -1] [list 0 3 1 5 2 4] [list 1 -1 1 -1 1 1]]
set ::tab::rot(A2) [list [list 0 4 5 2 3 1] [list 1 1 1 -1 -1 1] [list 0 5 3 4 1 2] [list 1 1 -1 -1 1 1]]
set ::tab::rot(A-1) [list [list 0 3 1 5 2 4] [list 1 -1 1 -1 1 1] [list 0 2 4 1 5 3] [list 1 1 1 -1 1 -1]]
set ::tab::rot(A-2) [list [list 0 5 3 4 1 2] [list 1 1 -1 -1 1 1] [list 0 4 5 2 3 1] [list 1 1 1 -1 -1 1]]
set ::tab::rot(B1) [list [list 3 1 0 4 5 2] [list -1 1 1 1 1 -1] [list 2 1 5 0 3 4] [list 1 1 -1 -1 1 1]]
set ::tab::rot(B2) [list [list 4 1 3 5 2 0] [list -1 1 -1 1 -1 -1] [list 5 1 4 2 0 3] [list -1 1 -1 -1 -1 1]]
set ::tab::rot(B-1) [list [list 2 1 5 0 3 4] [list 1 1 -1 -1 1 1] [list 3 1 0 4 5 2] [list -1 1 1 1 1 -1]]
set ::tab::rot(B-2) [list [list 5 1 4 2 0 3] [list -1 1 -1 -1 -1 1] [list 4 1 3 5 2 0] [list -1 1 -1 1 -1 -1]]
set ::tab::rot(C1) [list [list 1 5 2 4 0 3] [list 1 -1 1 1 1 -1] [list 4 0 2 5 3 1] [list 1 1 1 -1 1 -1]]
set ::tab::rot(C2) [list [list 5 3 2 0 1 4] [list -1 1 1 1 1 -1] [list 3 4 2 1 5 0] [list 1 1 1 1 -1 -1]]
set ::tab::rot(C-1) [list [list 4 0 2 5 3 1] [list 1 1 1 -1 1 -1] [list 1 5 2 4 0 3] [list 1 -1 1 1 1 -1]]
set ::tab::rot(C-2) [list [list 3 4 2 1 5 0] [list 1 1 1 1 -1 -1] [list 5 3 2 0 1 4] [list -1 1 1 1 1 -1]]
set ::tab::rot(D1) [list [list 1 4 5 3 2 0] [list 1 -1 -1 1 1 1] [list 5 0 4 3 1 2] [list 1 1 1 1 -1 -1]]
set ::tab::rot(D2) [list [list 4 2 0 3 5 1] [list -1 -1 -1 1 -1 1] [list 2 5 1 3 0 4] [list -1 1 -1 1 -1 -1]]
set ::tab::rot(D-1) [list [list 5 0 4 3 1 2] [list 1 1 1 1 -1 -1] [list 1 4 5 3 2 0] [list 1 -1 -1 1 1 1]]
set ::tab::rot(D-2) [list [list 2 5 1 3 0 4] [list -1 1 -1 1 -1 -1] [list 4 2 0 3 5 1] [list -1 -1 -1 1 -1 1]]
set ::tab::rot(E1) [list [list 2 5 3 1 4 0] [list 1 -1 1 -1 1 1] [list 5 3 0 2 4 1] [list 1 -1 1 1 1 -1]]
set ::tab::rot(E2) [list [list 3 0 1 5 4 2] [list 1 -1 -1 1 1 1] [list 1 2 5 0 4 3] [list -1 -1 1 1 1 1]]
set ::tab::rot(E-1) [list [list 5 3 0 2 4 1] [list 1 -1 1 1 1 -1] [list 2 5 3 1 4 0] [list 1 -1 1 -1 1 1]]
set ::tab::rot(E-2) [list [list 1 2 5 0 4 3] [list -1 -1 1 1 1 1] [list 3 0 1 5 4 2] [list 1 -1 -1 1 1 1]]
set ::tab::rot(F1) [list [list 4 2 3 0 1 5] [list 1 1 1 -1 -1 1] [list 3 4 1 2 0 5] [list -1 -1 1 1 1 1]]
set ::tab::rot(F2) [list [list 1 3 0 4 2 5] [list -1 1 -1 -1 -1 1] [list 2 0 4 1 3 5] [list -1 -1 -1 1 -1 1]]
set ::tab::rot(F-1) [list [list 3 4 1 2 0 5] [list -1 -1 1 1 1 1] [list 4 2 3 0 1 5] [list 1 1 1 -1 -1 1]]
set ::tab::rot(F-2) [list [list 2 0 4 1 3 5] [list -1 -1 -1 1 -1 1] [list 1 3 0 4 2 5] [list -1 1 -1 -1 -1 1]]

# --- 20 vertex-axis 3-fold rotations ---
set ::tab::rot(ABC1) [list [list 2 0 1 4 5 3] [list 1 1 1 -1 -1 1] [list 1 2 0 5 3 4] [list 1 1 1 1 -1 -1]]
set ::tab::rot(ABC-1) [list [list 1 2 0 5 3 4] [list 1 1 1 1 -1 -1] [list 2 0 1 4 5 3] [list 1 1 1 -1 -1 1]]
set ::tab::rot(ABD1) [list [list 1 3 4 0 5 2] [list 1 -1 -1 -1 -1 1] [list 3 0 5 1 2 4] [list -1 1 1 -1 -1 -1]]
set ::tab::rot(ABD-1) [list [list 3 0 5 1 2 4] [list -1 1 1 -1 -1 -1] [list 1 3 4 0 5 2] [list 1 -1 -1 -1 -1 1]]
set ::tab::rot(ACE1) [list [list 4 5 0 1 2 3] [list 1 1 1 1 1 1] [list 2 3 4 5 0 1] [list 1 1 1 1 1 1]]
set ::tab::rot(ACE-1) [list [list 2 3 4 5 0 1] [list 1 1 1 1 1 1] [list 4 5 0 1 2 3] [list 1 1 1 1 1 1]]
set ::tab::rot(ADF1) [list [list 3 2 4 5 1 0] [list -1 -1 -1 -1 1 1] [list 5 4 1 0 2 3] [list 1 1 -1 -1 -1 -1]]
set ::tab::rot(ADF-1) [list [list 5 4 1 0 2 3] [list 1 1 -1 -1 -1 -1] [list 3 2 4 5 1 0] [list -1 -1 -1 -1 1 1]]
set ::tab::rot(AEF1) [list [list 5 2 3 1 0 4] [list 1 -1 -1 1 1 1] [list 4 3 1 2 5 0] [list 1 1 -1 -1 1 1]]
set ::tab::rot(AEF-1) [list [list 4 3 1 2 5 0] [list 1 1 -1 -1 1 1] [list 5 2 3 1 0 4] [list 1 -1 -1 1 1 1]]
set ::tab::rot(BCF1) [list [list 3 2 5 4 0 1] [list 1 1 -1 -1 -1 -1] [list 4 5 1 0 3 2] [list -1 -1 1 1 -1 -1]]
set ::tab::rot(BCF-1) [list [list 4 5 1 0 3 2] [list -1 -1 1 1 -1 -1] [list 3 2 5 4 0 1] [list 1 1 -1 -1 -1 -1]]
set ::tab::rot(BDE1) [list [list 5 4 0 1 3 2] [list -1 -1 -1 -1 1 1] [list 2 3 5 4 1 0] [list -1 -1 1 1 -1 -1]]
set ::tab::rot(BDE-1) [list [list 2 3 5 4 1 0] [list -1 -1 1 1 -1 -1] [list 5 4 0 1 3 2] [list -1 -1 -1 -1 1 1]]
set ::tab::rot(BEF1) [list [list 3 5 0 2 1 4] [list 1 -1 -1 -1 -1 1] [list 2 4 3 0 5 1] [list -1 -1 -1 1 1 -1]]
set ::tab::rot(BEF-1) [list [list 2 4 3 0 5 1] [list -1 -1 -1 1 1 -1] [list 3 5 0 2 1 4] [list 1 -1 -1 -1 -1 1]]
set ::tab::rot(CDE1) [list [list 1 5 4 2 3 0] [list -1 1 1 1 1 -1] [list 5 0 3 4 2 1] [list -1 -1 1 1 1 1]]
set ::tab::rot(CDE-1) [list [list 5 0 3 4 2 1] [list -1 -1 1 1 1 1] [list 1 5 4 2 3 0] [list -1 1 1 1 1 -1]]
set ::tab::rot(CDF1) [list [list 1 4 3 5 0 2] [list -1 1 1 -1 -1 -1] [list 4 0 5 2 1 3] [list -1 -1 -1 1 1 -1]]
set ::tab::rot(CDF-1) [list [list 4 0 5 2 1 3] [list -1 -1 -1 1 1 -1] [list 1 4 3 5 0 2] [list -1 1 1 -1 -1 -1]]

# --- 15 edge-axis 2-fold flips ---
set ::tab::rot(AB) [list [list 0 1 3 2 5 4] [list -1 -1 1 1 -1 -1] [list 0 1 3 2 5 4] [list -1 -1 1 1 -1 -1]]
set ::tab::rot(AC) [list [list 0 4 2 5 1 3] [list -1 -1 -1 1 -1 1] [list 0 4 2 5 1 3] [list -1 -1 -1 1 -1 1]]
set ::tab::rot(AD) [list [list 0 5 4 3 2 1] [list -1 -1 -1 -1 -1 -1] [list 0 5 4 3 2 1] [list -1 -1 -1 -1 -1 -1]]
set ::tab::rot(AE) [list [list 0 3 5 1 4 2] [list -1 1 -1 1 -1 -1] [list 0 3 5 1 4 2] [list -1 1 -1 1 -1 -1]]
set ::tab::rot(AF) [list [list 0 2 1 4 3 5] [list -1 -1 -1 1 1 -1] [list 0 2 1 4 3 5] [list -1 -1 -1 1 1 -1]]
set ::tab::rot(BC) [list [list 5 1 2 4 3 0] [list 1 -1 -1 -1 -1 1] [list 5 1 2 4 3 0] [list 1 -1 -1 -1 -1 1]]
set ::tab::rot(BD) [list [list 4 1 5 3 0 2] [list 1 -1 1 -1 1 1] [list 4 1 5 3 0 2] [list 1 -1 1 -1 1 1]]
set ::tab::rot(BE) [list [list 2 1 0 5 4 3] [list -1 -1 -1 -1 -1 -1] [list 2 1 0 5 4 3] [list -1 -1 -1 -1 -1 -1]]
set ::tab::rot(BF) [list [list 3 1 4 0 2 5] [list 1 -1 1 1 1 -1] [list 3 1 4 0 2 5] [list 1 -1 1 1 1 -1]]
set ::tab::rot(CD) [list [list 1 0 2 3 5 4] [list -1 -1 -1 -1 1 1] [list 1 0 2 3 5 4] [list -1 -1 -1 -1 1 1]]
set ::tab::rot(CE) [list [list 3 5 2 0 4 1] [list -1 1 -1 -1 -1 1] [list 3 5 2 0 4 1] [list -1 1 -1 -1 -1 1]]
set ::tab::rot(CF) [list [list 4 3 2 1 0 5] [list -1 -1 -1 -1 -1 -1] [list 4 3 2 1 0 5] [list -1 -1 -1 -1 -1 -1]]
set ::tab::rot(DE) [list [list 5 2 1 3 4 0] [list -1 1 1 -1 -1 -1] [list 5 2 1 3 4 0] [list -1 1 1 -1 -1 -1]]
set ::tab::rot(DF) [list [list 2 4 0 3 1 5] [list 1 1 1 -1 1 -1] [list 2 4 0 3 1 5] [list 1 1 1 -1 1 -1]]
set ::tab::rot(EF) [list [list 1 0 3 2 4 5] [list 1 1 -1 -1 -1 -1] [list 1 0 3 2 4 5] [list 1 1 -1 -1 -1 -1]]
