// Generated by CoffeeScript 2.7.0
// phiBase.coffee
// Represents numbers of the form (p * φ + n)
var ONE, PHI, PhiBase, ZERO;

PHI = (1 + Math.sqrt(5)) / 2;

PhiBase = (function() {
  var maxOrder, tolerance;

  class PhiBase {
    constructor(p, n) {
      this.p = p;
      this.n = n;
    }

    clone() {
      return new PhiBase(this.p, this.n);
    }

    add(other) {
      return new PhiBase(this.p + other.p, this.n + other.n);
    }

    sub(other) {
      return new PhiBase(this.p - other.p, this.n - other.n);
    }

    negate() {
      return new PhiBase(-this.p, -this.n);
    }

    scale(c) {
      if (c instanceof PhiBase) {
        return this.mul(c);
      } else {
        return new PhiBase(this.p * c, this.n * c);
      }
    }

    step(incr = 1) {
      var nIncr, phiValue;
      phiValue = (this.p + 1) * PhiBase.PHI;
      nIncr = this.n + incr;
      if (nIncr < phiValue) {
        return new PhiBase(this.p, nIncr);
      } else {
        return new PhiBase(this.p + 1, this.n);
      }
    }

    mul(other) {
      // (p1 * φ + n1) * (p2 * φ + n2) = (p1*n2 + n1*p2 + p1*p2) * φ + (n1*n2 + p1*p2)
      return new PhiBase(this.p * other.n + this.n * other.p + this.p * other.p, this.n * other.n + this.p * other.p);
    }

    conjugate() {
      return new PhiBase(-this.p, this.p + this.n);
    }

    div(other, allow = false) {
      var denomValue, newDenominator, newNumerator, phiMinusOne, resultN, resultP;
      if (other.p === 0 && other.n === 1) {
        return this.clone();
      }
      // Phi-algebra division
      phiMinusOne = new PhiBase(1, -1);
      newNumerator = this.mul(phiMinusOne);
      newDenominator = other.mul(phiMinusOne);
      denomValue = newDenominator.toFloat();
      if (denomValue === 0) {
        throw new Error("Division by zero in PhiBase");
      }
      resultP = newNumerator.p / denomValue;
      resultN = newNumerator.n / denomValue;
      return new PhiBase(resultP, resultN);
    }

    equals(other) {
      var ee;
      ee = function(xx) {
        return Math.trunc(xx * 1000);
      };
      ee = function(xx) {
        return Math.sign(xx) * Math.round(Math.abs(xx) * 1000);
      };
      return ee(this.p) === ee(other.p) && ee(this.n) === ee(other.n);
    }

    toFloat() {
      return this.p * PHI + this.n;
    }

    toName() {
      var ee;
      ee = function(xx) {
        return Math.trunc(xx * 1000);
      };
      ee = function(xx) {
        return Math.sign(xx) * Math.round(Math.abs(xx) * 1000);
      };
      return `${ee(this.p)}φ,` + `${ee(this.n)}`;
    }

    toString() {
      var parts;
      parts = [];
      if (this.p !== 0) {
        parts.push(`${this.p}φ`);
      }
      if (this.n !== 0) {
        parts.push(`${this.n}`);
      }
      return parts.join(' + ') || '0';
    }

    static fromFloat1(num, tolerance = 1e-8) {
      var best, bestErr, candVal, candidate, err, neg, x;
      neg = false;
      if (num < 0) {
        neg = true;
        num = -num; // Work with positive value only
      }
      x = new PhiBase(0, 0);
      best = x;
      bestErr = Math.abs(x.toFloat() - num);
      while (true) {
        candidate = x.step();
        candVal = candidate.toFloat();
        err = Math.abs(candVal - num);
        if (err < bestErr) {
          best = candidate;
          bestErr = err;
          x = candidate;
        } else {
          break;
        }
      }
      if (neg) {
        return best.scale(-1); // Negate the result if input was negative
      } else {
        return best;
      }
    }

  };

  PhiBase.PHI = PHI;

  // Useful constants
  PhiBase.ZERO = new PhiBase(0, 0);

  PhiBase.ONE = new PhiBase(0, 1);

  PhiBase.fromFloat(num, tolerance = 1e-6, maxOrder = 20)(function() {
    var F, best, delta, error, j, k, l, m, n, p, ref, ref1, testN, testP, val;
    best = {
      p: 0,
      n: 0,
      value: 0,
      error: 2e308
    };
    F = [0, 1];
    for (k = j = 2, ref = maxOrder; (2 <= ref ? j <= ref : j >= ref); k = 2 <= ref ? ++j : --j) {
      F[k] = F[k - 1] + F[k - 2];
    }
    for (k = l = 2, ref1 = maxOrder; (2 <= ref1 ? l <= ref1 : l >= ref1); k = 2 <= ref1 ? ++l : --l) {
      p = F[i];
      n = -F[i + 1];
      for (delta = m = -2; m <= 2; delta = ++m) {
        testP = p + delta;
        testN = n + Math.round(num - testP * phi);
        val = testP * phi + testN;
        error = Math.abs(val - num);
        if (error < best.error) {
          best = new PhiBase(testP, testN);
          best.value = val;
          if (error < tolerance) {
            return best;
          }
        }
      }
    }
    return best;
  });

  return PhiBase;

}).call(this);


// Useful constants
ZERO = new PhiBase(0, 0);

ONE = new PhiBase(0, 1);

export {
  PHI,
  PhiBase,
  ZERO,
  ONE
};
