// Generated by CoffeeScript 2.7.0
var Phi, cliqueNames, cliques, cnames, createCliques, decode, fe, splitName, stripName;

import {
  Memo
} from './memo.coffee';

import _ from 'underscore';

import * as seenModule from '$lib/seen.m.coffee';

export var M = new Memo();

fe = (Math.sqrt(5) - 1) / 2.0;

Phi = (1 + Math.sqrt(5)) / 2;

//  "Z": 0
decode = {
  "z": 0,
  "O": 1,
  "o": -1,
  "f": -1 / Phi,
  "F": 1 / Phi,
  "G": Phi + 1 / Phi,
  "g": -Phi - 1 / Phi,
  "H": 1 - 1 / Phi,
  "h": -1 + 1 / Phi,
  "p": -Phi,
  "P": Phi
};

/*
  Memo API
  saveThis: (key, value)->
  theLowdown: (key)=> returns current info on value at key
  waitFor: (aList,andDo)=> wait for updates to ANY of the aList and call andDo via promise
  notifyMe: (n,andDo)=>
*/

//convert a string like "#FPz-#Fpz-..." into an array of point names
splitName = function(longName) {
  var value;
  value = longName.split(/-|<|>/);
  return value;
};

cliques = {};

cliqueNames = [];

cnames = [];

stripName = function(sID, tID) {
  var rValue, segParts;
  segParts = sID.split(/>|-|</g);
  rValue = tID.split(/<|>|-/g).join('').replace(segParts[0], '').replace(segParts[1], '');
  return rValue;
};

createCliques = function(G) {
  var cV, cVmS, cantidateTriangle, cantidates, cc, idx, l, lDiff, len, len1, len2, len3, masterTriangle, n, o, q, ref, ref1, s, sV, sVmS, zz;
  if (!G.fiboTriangles.length) {
    return [];
  }
  cantidates = G.fiboTriangles.slice(0);
  for (l = 0, len = cantidates.length; l < len; l++) {
    masterTriangle = cantidates[l];
    ref = masterTriangle.value.segments;
    for (idx = n = 0, len1 = ref.length; n < len1; idx = ++n) {
      s = ref[idx];
      sV = (M.theLowdown(s)).value.vetric;
      sVmS = sV.magnitudeSquared();
      cliques[s] = {
        [`${masterTriangle.value.ID}`]: s
      };
      for (o = 0, len2 = cantidates.length; o < len2; o++) {
        cantidateTriangle = cantidates[o];
        ref1 = cantidateTriangle.value.segments;
        for (q = 0, len3 = ref1.length; q < len3; q++) {
          cc = ref1[q];
          cV = (M.theLowdown(cc)).value.vetric;
          // cross product detects parallel segments
          zz = sV.copy().cross(cV);
          cVmS = cV.magnitudeSquared();
          lDiff = Math.abs(cVmS - sVmS);
          if (lDiff < 0.1 && zz.magnitudeSquared() < 0.1) {
            cliques[s][cantidateTriangle.value.ID] = [cc, stripName(cc, cantidateTriangle.value.ID)];
          }
        }
      }
    }
  }
  cnames = (function() {
    var results;
    results = [];
    for (s in cliques) {
      results.push(s);
    }
    return results;
  })();
  cliqueNames = cnames.slice();
  return {cliques, cliqueNames};
};

export var Geo = (function() {
  var cube, dodecahedron1, dodecahedron2, icosahedron1, icosahedron2, itemsConstructed, movedTriangles, octahedron, pentagon, square, tetrahedron1, tetrahedron1Faces, tetrahedron2;

  class Geo {
    /*+
     * param: ptxt encoding of essential points above text
     * returns new seen.P decorated with ID: ptxt
     * side-effect: adds point to pointName map to this returned value
     */
    createSeenPoint(ptxt, shapeName = "") {
      var p, xyz;
      if (!(xyz = ptxt.match('#(.)(.)(.)(X[0-9]+)?$'))) {
        return null;
      }
      if (null !== (p = (M.theLowdown(ptxt)).value)) {
        p.shapeName[shapeName] = shapeName;
        return (M.theLowdown(ptxt)).value;
      }
      p = seen.P(decode[xyz[1]], decode[xyz[2]], decode[xyz[3]]);
      p.d = p.magnitude().toFixed(3);
      p.shapeName = {
        [`${shapeName}`]: shapeName
      };
      p.ID = ptxt;
      return (M.saveThis(ptxt, p)).value; //return just the point value, not the meta info
    }

    /*
     * formPointsFrom creates entries in the Memo
     * from the point sets of the shape
     * the originating shape name is used as a tag in the Memo
     */
    formPointsFrom(shape, shapeName = "") {
      var i, shapePoints;
      shapePoints = (function() {
        var l, len, ref, results;
        ref = shape.split(/-|>|</);
        results = [];
        for (l = 0, len = ref.length; l < len; l++) {
          i = ref[l];
          results.push(this.createSeenPoint(i, shapeName));
        }
        return results;
      }).call(this);
      return (M.saveThis(shapeName, shapePoints)).value;
    }

    getPointAt(m) {
      if (M.MM[m] != null) {
        return M.MM[m].value;
      }
      return null;
    }

    /*
     * createSegment:
     * creates two seenpoints from the two ID's
     * the resulting seenpoints are stored into the Memo as an array
     * with attributes ID, d for magnitude (to 3 digits) 
     *
     * the vetric is used to detect parallel segments to create cliques
     * midPoint is used to translate any clique element to a cannonical position
     * for further translation in 3space. it is the midpoint of the segment.
     */
    createSegment(ptxt1, ptxt2) {
      var ID, midPoint, p1, p2, points, t, vetric;
      if (typeof ptxt1 === 'object') {
        ptxt2 = ptxt1[1];
        ptxt1 = ptxt1[0];
      }
      if (ptxt2 < ptxt1) {
        (t = ptxt1, ptxt1 = ptxt2, ptxt2 = t);
      }
      ID = `${ptxt1}-${ptxt2}`;
      if (M.MM[ID]) {
        return ID;
      }
      p1 = this.createSeenPoint(ptxt1);
      p2 = this.createSeenPoint(ptxt2);
      points = [p1, p2];
      vetric = p1.copy().subtract(p2);
      midPoint = p1.copy().add(p2).divide(2);
      M.saveThis(ID, {ID, points, vetric, midPoint});
      return ID;
    }

    moveSegment(segmentName, seenDestination, sID = null) {
      var ID, midPoint, path, residual, segment, unlessSegment, vetric;
      segment = M.MM[segmentName].value;
      midPoint = segment.midPoint;
      vetric = segment.vetric;
      if (seenDestination.constructor.name === "Point") {
        path = [segment.points[0].copy().subtract(midPoint).add(seenDestination), segment.points[1].copy().subtract(midPoint).add(seenDestination)];
      } else {
        path = seenDestination;
      }
      midPoint = path[0].copy().add(path[1]).divide(2);
      if (sID) {
        unlessSegment = M.MM[sID].value;
        residual = unlessSegment.midPoint.copy().subtract(midPoint).magnitudeSquared();
        if (residual > 0.1) {
          ID = segmentName + "X" + itemsConstructed++;
          M.saveThis(ID, {ID, seenDestination, path, midPoint, vetric});
        } else {
          ID = null;
        }
      } else {
        ID = segmentName + "X" + itemsConstructed++;
        M.saveThis(ID, {ID, seenDestination, path, midPoint, vetric});
      }
      return ID;
    }

    normalizeFrame(points, bias = null) {
      var l, len, r, ref, results, s;
      if ((bias != null ? (ref = bias.constructor) != null ? ref.name : void 0 : void 0) !== "Point") {
        bias = seen.P();
      }
      results = [];
      for (l = 0, len = points.length; l < len; l++) {
        s = points[l];
        if ("Point" === s.constructor.name) {
          r = bias.copy().add(s);
          r.ID = s.ID;
          results.push(r);
        } else {
          r = bias.copy().add(this.createSeenPoint(s));
          r.ID = s;
          results.push(r);
        }
      }
      return results;
    }

    moveTriangle(sID, tID) {
      var ID, face, nickName, offsetSegment, path, s1, s2, s3, sMidPoint, segment, segments, tMidPoint, triangle, value;
      triangle = M.MM[tID].value;
      segment = M.MM[sID].value;
      path = this.normalizeFrame(tID.split(/-|<|>/));
      nickName = (sID.split('X'))[0];
      offsetSegment = this.cliques[nickName][tID][0];
      tMidPoint = M.MM[offsetSegment].value.midPoint;
      sMidPoint = M.MM[nickName].value.midPoint;
      path = path.map(function(p) {
        return p.copy().subtract(tMidPoint).add(segment.midPoint);
      });
      s1 = this.moveSegment(triangle.segments[0], [path[0], path[1]], sID);
      s2 = this.moveSegment(triangle.segments[1], [path[1], path[2]], sID);
      s3 = this.moveSegment(triangle.segments[2], [path[0], path[2]], sID);
      segments = [];
      if (s1) {
        segments.push(s1);
      }
      if (s2) {
        segments.push(s2);
      }
      if (s3) {
        segments.push(s3);
      }
      ID = tID + "--" + movedTriangles++;
      face = triangle.face;
      ({value} = M.saveThis(ID, {ID, face, segments, path}));
      return value;
    }

    /*
     * createSegments:
     * iterates through all the points (seen.P) created by createPoint
     * and splices each into all the segments those points create
     * creates Object theSegments with all the segments keyed by the endpoint names
     * creates Object segmentsByMagnitude with all segments sorted and grouped by magnitude
     * theSegments are used in the actual drawing
     * segmentsByMagnitude select the segments to be drawn
     * segments are stored in the Memo with keys of the form '#ppp-#ppp' with end point names ppp
     */
    createSegments(points) {
      var i, j, keySort, l, len, len1, n, p1, p2, segmentNames, segmentsByMagnitude, tag, theSegments;
      theSegments = {};
      for (i = l = 0, len = points.length; l < len; i = ++l) {
        p1 = points[i];
        for (j = n = 0, len1 = points.length; n < len1; j = ++n) {
          p2 = points[j];
          if (p1 === p2) {
            continue;
          }
          tag = this.createSegment(p1.ID, p2.ID);
          theSegments[tag] = M.MM[tag];
        }
      }
      segmentsByMagnitude = _.chain(theSegments).map(function(v) {
        return v.value;
      }).sortBy('vetric').groupBy('vetric');
      keySort = function(k, v) {
        return +v < +k;
      };
      segmentNames = segmentsByMagnitude.keys().sort(keySort).value();
      segmentsByMagnitude = segmentsByMagnitude.value();
      return {segmentNames, segmentsByMagnitude};
    }

    angleBetween(localOrigin, segmentID0, segmentID1) {
      var angleDeg, dot, localOriginData, raw, seg0Vector, seg1Vector, v0, v1;
      // get the underlying seen value
      localOriginData = M.MM[localOrigin].value;
      seg0Vector = M.MM[segmentID0].value;
      seg1Vector = M.MM[segmentID1].value;
      v0 = seg0Vector.copy().subtract(localOriginData);
      v1 = seg1Vector.copy().subtract(localOriginData);
      dot = v1.dot(v0);
      raw = dot / (v1.magnitude() * v0.magnitude());
      // angle in radians
      //angleRadians = Math.atan2(p2.y - p1.y, p2.x - p1.x);
      // angle in degrees
      angleDeg = Math.acos(raw) * 180 / Math.PI;
      return angleDeg = angleDeg.toFixed(3);
    }

    createTriangle(p1, p2, p3, face) {
      debugger;
      var ID, key, s1, s2, s3;
      key = [p1, p2, p3].sort();
      p1 = key[0];
      p2 = key[1];
      p3 = key[2];
      s1 = this.createSegment(p1, p2);
      s2 = this.createSegment(p2, p3);
      s3 = this.createSegment(p1, p3);
      ID = `${p1}>${p2}>${p3}`;
      return M.saveThis(ID, {
        ID: ID,
        path: [p1, p2, p3],
        segments: [s1, s2, s3],
        face: face
      });
    }

    // createAngles takes points, and segments .  it returns the angle that the segment makes from the point.
    // all the open triangles that are inspected are sorted by angle magnitude
    // the magnitudes are sorted and converted into groups of angles
    createAngles(points, segments) {
      var ID, angleNames, anglesByMagnitude, biVectors, d, i, j, keySort, l, leg0, leg1, len, len1, n, path, seg0Vector, seg1Vector;
      biVectors = {};
      for (l = 0, len = points.length; l < len; l++) {
        i = points[l];
        for (n = 0, len1 = segments.length; n < len1; n++) {
          j = segments[n];
          if (!(j != null ? j.ID : void 0)) {
            continue;
          }
          [leg0, leg1] = j.ID.split(/-|<|>/);
          if (i.ID === leg0 || i.ID === leg1) {
            continue;
          }
          d = this.angleBetween(i.ID, leg0, leg1);
          ID = `${i.ID}<${leg0}-${leg1}`;
          seg0Vector = M.MM[leg0].value;
          seg1Vector = M.MM[leg1].value;
          path = [seg0Vector, i, seg1Vector];
          M.saveThis(ID, {ID, path, d});
          biVectors[ID] = M.MM[ID];
        }
      }
      anglesByMagnitude = _.chain(biVectors).map(function(v) {
        return v.value;
      }).sortBy('d').groupBy('d');
      keySort = function(k, v) {
        return +v < +k;
      };
      angleNames = anglesByMagnitude.keys().sort(keySort).value();
      anglesByMagnitude = anglesByMagnitude.value();
      return {angleNames, anglesByMagnitude};
    }

    makeHut(points, value, coordinateID, inner) { //left top, right top, left bottom,right bottom
      var ex, makeT, mapp, pb, pbID, pl, plID, pr, prID, pt, ptID, wy;
      mapp = [0, 1, 2, 0, 1];
      ex = mapp[coordinateID + 1];
      wy = mapp[coordinateID + 2];
      pt = [];
      pt[coordinateID] = inner[0];
      pt[ex] = 'F';
      pt[wy] = 'z';
      ptID = '#' + pt.join('');
      pl = [];
      pl[coordinateID] = inner[1];
      pl[ex] = 'z';
      pl[wy] = 'F';
      plID = '#' + pl.join('');
      pr = [];
      pr[coordinateID] = inner[1];
      pr[ex] = 'z';
      pr[wy] = 'f';
      prID = '#' + pr.join('');
      pb = [];
      pb[coordinateID] = inner[0];
      pb[ex] = 'f';
      pb[wy] = 'z';
      pbID = '#' + pb.join('');
      makeT = (p1, p2, p3, belongsTo = "hut") => {
        var t1;
        t1 = this.createTriangle(p1, p2, p3, p3);
        return this.Faces[t1.value.ID] = p3;
      };
      makeT(points[0][0], ptID, pbID);
      makeT(points[0][1], ptID, pbID);
      makeT(points[1][0], ptID, pbID);
      makeT(points[1][1], ptID, pbID);
      makeT(points[0][0], points[0][1], ptID);
      makeT(points[1][0], points[1][1], pbID);
      makeT(points[0][0], points[1][0], ptID);
      makeT(points[0][1], points[1][1], pbID);
      makeT(points[0][1], points[1][1], ptID);
      makeT(points[0][0], points[1][0], pbID);
      makeT(points[0][0], plID, prID);
      makeT(points[0][1], plID, prID);
      makeT(points[1][0], plID, prID);
      makeT(points[1][1], plID, prID);
      makeT(points[0][0], points[1][0], plID);
      makeT(points[0][1], points[1][1], prID);
      makeT(points[1][0], points[1][1], prID);
      makeT(points[0][0], points[0][1], plID);
      makeT(points[1][0], points[1][1], plID);
      return makeT(points[0][0], points[0][1], prID);
    }

    examineFaces() {
      var f0, inner, l, len, len1, len2, n, o, ones, results, x, y, z;
      ones = "Oo";
      inner = "PH";
      for (l = 0, len = ones.length; l < len; l++) {
        x = ones[l];
        f0 = (function() {
          var len1, n, results;
          results = [];
          for (n = 0, len1 = ones.length; n < len1; n++) {
            y = ones[n];
            results.push((function() {
              var len2, o, results1;
              results1 = [];
              for (o = 0, len2 = ones.length; o < len2; o++) {
                z = ones[o];
                results1.push("#" + x + y + z);
              }
              return results1;
            })());
          }
          return results;
        })();
        this.makeHut(f0, x, 0, inner);
        inner = "ph";
      }
      inner = "PH";
      for (n = 0, len1 = ones.length; n < len1; n++) {
        y = ones[n];
        f0 = (function() {
          var len2, o, results;
          results = [];
          for (o = 0, len2 = ones.length; o < len2; o++) {
            z = ones[o];
            results.push((function() {
              var len3, q, results1;
              results1 = [];
              for (q = 0, len3 = ones.length; q < len3; q++) {
                x = ones[q];
                results1.push("#" + x + y + z);
              }
              return results1;
            })());
          }
          return results;
        })();
        this.makeHut(f0, y, 1, inner);
        inner = "ph";
      }
      inner = "PH";
      results = [];
      for (o = 0, len2 = ones.length; o < len2; o++) {
        z = ones[o];
        f0 = (function() {
          var len3, q, results1;
          results1 = [];
          for (q = 0, len3 = ones.length; q < len3; q++) {
            x = ones[q];
            results1.push((function() {
              var len4, results2, u;
              results2 = [];
              for (u = 0, len4 = ones.length; u < len4; u++) {
                y = ones[u];
                results2.push("#" + x + y + z);
              }
              return results2;
            })());
          }
          return results1;
        })();
        this.makeHut(f0, z, 2, inner);
        results.push(inner = "ph");
      }
      return results;
    }

    /*
    */
    // create the fiboTriangles on each of the 12 faces
    createFiboTriangles(faces) {
      var all, face, i, itms, j, l, n, names, ref, sa;
      all = [];
      for (sa in faces) {
        face = faces[sa];
        names = splitName(sa);
        if (names.length === 3) {
          all.push([this.createTriangle(names[0], names[1], names[2], face)]);
          continue;
        }
        itms = [...names, ...names];
        for (i = l = 0, ref = names.length + 1; (0 <= ref ? l <= ref : l >= ref); i = 0 <= ref ? ++l : --l) {
          for (j = n = 2; n <= 3; j = ++n) {
            all.push(this.createTriangle(itms[i], itms[i + 1], itms[i + j], sa));
          }
        }
      }
      return all.flat();
    }

    constructor() {
      this.Polyhedra = {
        Tetrahedron1: this.formPointsFrom(tetrahedron1, "tetrahedron"),
        Octahedron: this.formPointsFrom(octahedron, "octahedron"),
        Cube: this.formPointsFrom(cube, "cube"),
        Icosahedron1: this.formPointsFrom(icosahedron1, "icosahedron"),
        Dodecahedron1: this.formPointsFrom(dodecahedron1, "dodecahedron"),
        Tetrahedron2: this.formPointsFrom(tetrahedron2, "tetrahedron"),
        Icosahedron2: this.formPointsFrom(icosahedron2, "icosahedron"),
        Dodecahedron2: this.formPointsFrom(dodecahedron2, "dodecahedron")
      };
    }

  };

  square = "#ffz-#Ffz-#FFz-#fFz";

  pentagon = "#zFP-#OOO-#PzF-#OoO-#zfP";

  octahedron = "#O00-#o00-#0o0-#0O0-#00o-#00O";

  cube = "#OOO-#oOO-#OoO-#ooO-#OOo-#oOo-#Ooo-#ooo";

  tetrahedron1 = "#ooo-#oOO-#OoO-#OOo";

  tetrahedron2 = "#OOO-#Ooo-#oOo-#ooO";

  icosahedron1 = "#zOF-#zoF-#zof-#zOf-#oFz-#ofz-#OFz-#Ofz-#FzO-#fzO-#Fzo-#fzo";

  icosahedron2 = "#zFO-#zFo-#zfo-#zfO-#Foz-#foz-#FOz-#fOz-#OzF-#Ozf-#ozF-#ozf";

  dodecahedron1 = "#ooo-#ooO-#oOo-#oOO-#Ooo-#OoO-#OOo-#OOO-#zfp-#zFp-#zfP-#zFP-#pzf-#Pzf-#pzF-#PzF-#fpz-#Fpz-#fPz-#FPz";

  dodecahedron2 = "#ooo-#oOo-#ooO-#oOO-#Ooo-#OOo-#OoO-#OOO-#zpf-#zpF-#zPf-#zPF-#fzp-#fzP-#Fzp-#FzP-#pfz-#pFz-#Pfz-#PFz";

  tetrahedron1Faces = {
    "#ooo-#zzz-#oOO": {
      face: "0"
    },
    "#ooo-#zzz-#OOo": {
      face: "1"
    },
    "#ooo-#zzz-#OoO": {
      face: "2"
    },
    "#OoO-#zzz-#OOo": {
      face: "3"
    },
    "#OoO-#zzz-#oOO": {
      face: "4"
    },
    "#OOo-#zzz-#oOO": {
      face: "5"
    }
  };

  movedTriangles = 1;

  itemsConstructed = 0;

  Geo.Faces = {};

  Geo.examineFaces();

  // create the fiboTriangles on each of the 12 faces
  //@fiboTriangles= @createFiboTriangles @Faces
  ({cliques: Geo.cliques, cliqueNames: Geo.cliqueNames} = createCliques(Geo));

  return Geo;

}).call(this);

/*
@Faces=
    "#fff-#zzz-#fFF": "#fzF"
    "#fff-#zzz-#FFf": "#fzf"
    "#fff-#zzz-#FfF": "#fFz"
    "#FfF-#zzz-#FFf": "#FzF"
    "#FfF-#zzz-#fFF": "#Fzf"
    "#FFf-#zzz-#fFF": "#fFz"

    "#FFF-#zzz-#Fff": "#zfF"
    "#FFF-#zzz-#ffF": "#zff"
    "#FFF-#zzz-#fFf": "#Ffz"
    "#fFf-#zzz-#ffF": "#zFF"
    "#fFf-#zzz-#Fff": "#zFf"
    "#ffF-#zzz-#Fff": "#Ffz"

@Faces2= [
   "#ooO-#zfP-#OoO-#Fpz-#fpz",  # Face A
   "#oOo-#zFp-#OOo-#FPz-#fPz",   # Face a
   "#ooo-#fpz-#ooO-#pzF-#pzf",   #Face B
   "#OOo-#FPz-#OOO-#PzF-#Pzf",   #Face b
   "#ooo-#zfp-#Ooo-#Fpz-#fpz",    #Face C
   "#oOO-#zFP-#OOO-#FPz-#fPz",   #Face c
   "#Ooo-#Fpz-#OoO-#PzF-#Pzf",  # Face D
   "#oOo-#fPz-#oOO-#pzF-#pzf"   # Face d
   "#ooo-#pzf-#oOo-#zFp-#zfp",   #Face E
   "#OoO-#PzF-#OOO-#zFP-#zfP",   #Face e
   "#ooO-#pzF-#oOO-#zFP-#zfP",    #Face F
   "#Ooo-#Pzf-#OOo-#zFp-#zfp",  #Face f
  ]

*/
